name: OS Compatibility Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  comp_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'
          enable-cache: true
      - run: uv tool install branthebuilder
      - run: branb test
