name: OS Compatibility Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  comp_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.8'
          enable-cache: true
      - run: uv pip install -e .[test]
      - run: branb test
